# Site settings
author: David Mathew Anderson
title: Rising from the Ashes
header-img: img/home-bg.png
email: matandersonlv@hotmail.com
copyright_name: David Mathew Anderson
description: > # this means to ignore newlines until "baseurl:"
  My Journey  to becoming a Web Developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mat0829

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
